#!/bin/bash
PATH="/usr/local/bin:$PATH"
chmod +x "/Users/ernest/HISE/JUCE/Projucer/Projucer.app/Contents/MacOS/Projucer"
cd "`dirname "$0"`"

JUCER="AutogeneratedProject.jucer"
PTP_LIB="/Users/ernest/HisePersonal/Personal/Hise-PointToPoint-Hisenberg/DspNetworks/ThirdParty/src/PointToPoint/lib/Release/libCircuitModel.a"
PTP_HDR="../ThirdParty/src/PointToPoint"

# ============================================================
# Patch the .jucer BEFORE Projucer converts it to Xcode.
# This is the key insight: we modify the .jucer XML, then
# Projucer reads our modified version and generates an Xcode
# project that already has the correct linker flags baked in.
# ============================================================
if [ -f "$JUCER" ] && ! grep -q "CircuitModel" "$JUCER"; then
    echo "Patching $JUCER with PointToPoint library..."

    # Add extraLinkerFlags (full path to .a file) to the Xcode exporter
    sed -i '' "s|<XCODE_MAC |<XCODE_MAC extraLinkerFlags=\"$PTP_LIB\" |" "$JUCER"

    # Add headerPath to every CONFIGURATION block
    sed -i '' "s|<CONFIGURATION |<CONFIGURATION headerPath=\"$PTP_HDR\" |g" "$JUCER"

    echo "Patch complete."
else
    echo "Already patched or jucer not found, skipping."
fi

# Projucer now reads the patched .jucer and generates Xcode with flags included
"/Users/ernest/HISE/JUCE/Projucer/Projucer.app/Contents/MacOS/Projucer" --resave "$JUCER"

set -o pipefail
echo Compiling  Hise-PointToPoint ...
xcodebuild -project "Builds/MacOSX/Hise-PointToPoint-Hisenberg.xcodeproj" -configuration "Release" -jobs "8" | "/Users/ernest/HISE/tools/Projucer/xcbeautify"
